from Entities.usuarios_model import Usuarios
from Entities.configuracao_model import Configuracao
from Entities.frases_model import Frases
from Entities.usuarios_coins_model import UsuariosCoins
from Entities.lasted_cleaning import LastestCleaning
from Entities.humor_diario_model import HumorDiario